name: "fastapi-kafka"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    #    env_file:
    #      - .env
    #    volumes:
    #      - ../logs/orders_app:/project/logs
    ports:
      - "8000:8000"
    #    depends_on:
    #      - postgres
    #      - kafka
    #    entrypoint: [ "docker/wait-for-it.sh", "${KAFKA_HOST}:${KAFKA_PORT}", "--" ]
    command: "uvicorn src.app.main:app --host 0.0.0.0 --port 8000"



  #  order_worker:
  # TODO: использовать app-image
  #    build:
  #      context: ../
  #      dockerfile: docker/Dockerfile
  #    env_file:
  #      - .env
  ##    volumes:
  ##      - ../logs/order_worker:/project/logs
  #    depends_on:
  #      - postgres
  #      - kafka
  #    entrypoint: [ "docker/wait-for-it.sh", "${KAFKA_HOST}:${KAFKA_PORT}", "--" ]
  #    command: "python -m src.run_consumer"

  postgres:
    image: postgres:17.7-alpine3.23
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  kafka:
    image: apache/kafka:4.1.1
    environment:
      #      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      #      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,EXTERNAL://localhost:9094

      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

      #      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

    ports:
      #      - "${KAFKA_PORT}:9092"
      #      - "${KAFKA_EXTERNAL_PORT}:9094" # нужен, если хотим запустить backend нативно, а кафку в докере (для разработки)
      - "9092:9092"
  #      - "9094:9094"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"
#    depends_on:
#      - kafka


volumes:
  postgres_data:
